version: "3.8"
services:
  mozjpeg:
    image: mozjpeg
    build: ./mozjpeg
    volumes:
      - ./deb-dist:/data:rw

  libtiff:
    image: libtiff
    build: ./libtiff
    links:
      - mozjpeg
    volumes:
      - ./deb-dist:/data:rw

  libwebp:
    image: libwebp
    build: ./libwebp
    links:
      - mozjpeg
      - libtiff
    volumes:
      - ./deb-dist:/data:rw

  jpegxl:
    image: jpegxl
    build: ./jpegxl
    links:
      - libwebp
    volumes:
      - ./deb-dist:/data:rw

  image_magick:
    image: image_magick
    container_name: image_magick
    build: ./ImageMagick
    links:
      - jpegxl
    volumes:
      - ./deb-dist:/data:rw