version: "3"
services:
  debbuilder:
    image: debbuilder
    build: .
    volumes:
      - ~/.ssh:/root/.ssh:rw
  mozjpeg:
    image: mozjpeg
    build: ./mozjpeg
    depends_on:
      - debbuilder
  jpegxl:
    image: jpegxl
    build: ./jpegxl
    depends_on:
      - mozjpeg