version: "3"
services:
  debbuilder:
    image: debbuilder
    container_name: debbuilder_base
    environment:
      DEBIAN_FRONTEND: noninteractive
      LANG: en_US.utf8
    build:
      context: .
  mozjpeg:
    image: mozjpeg
    container_name: mozjpeg
    build: ./mozjpeg
    links:
      - debbuilder

  libtiff:
    image: libtiff
    container_name: libtiff
    build: ./libtiff
    links:
      - mozjpeg

  libwebp:
    image: libwebp
    container_name: libwebp
    build: ./libwebp
    links:
      - mozjpeg
      - libtiff

  jpegxl:
    image: jpegxl
    container_name: jpegxl
    build: ./jpegxl
    links:
      - libwebp