version: "3"
services:
  debbuilder:
    image: debbuilder
    build: .
    volumes:
      - ~/.ssh:/root/.ssh:rw
  mozjpeg:
    image: mozjpeg
    build: ./mozjpeg
    depends_on:
      - debbuilder

  libtiff:
    image: libtiff
    build: ./libtiff
    depends_on:
      - mozjpeg
  libwebp:
    image: libwebp
    build: ./libwebp
    depends_on:
      - mozjpeg
      - libtiff
  jpegxl:
    image: jpegxl
    build: ./jpegxl
    depends_on:
      - libwebp